export const restrictionsDb: Array<Restriction> = [
  {
    id: 1,
    name: "Vegana",
    title: "Dieta vegana",
    image: require("@/assets/images/veganismo.jpg"),
    type: "dietary-pattern",
    description: "TODO",
  },
  {
    id: 2,
    name: "Vegetariana",
    title: "Dieta vegetariana",
    image: require("@/assets/images/dieta-vegetariana.jpg"),
    type: "dietary-pattern",
    description: "TODO",
  },
  {
    id: 3,
    name: "Ovolactovegetariana",
    title: "Dieta ovolactovegetariana",
    image: require("@/assets/images/ovolactovegetarianismo.jpg"),
    type: "dietary-pattern",
    description: "TODO",
  },
  {
    id: 4,
    name: "Onívora (comum)",
    title: "Dieta onívora (comum)",
    image: require("@/assets/images/dieta-onivora.jpg"),
    type: "dietary-pattern",
    description: "TODO",
  },
  {
    id: 5,
    name: "Outra",
    type: "dietary-pattern",
    description: "TODO",
  },
  {
    id: 6,
    name: "APLV",
    title: "Alergia a proteína do leite de vaca (APLV)",
    image: require("@/assets/images/leite-de-vaga.png"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 7,
    name: "Intolerância à lactose",
    title: "Intolerância à lactose",
    image: require("@/assets/images/intolerancia-a-lactose.jpg"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 8,
    name: "Alergia à amendoim",
    title: "Alergia à amendoim",
    image: require("@/assets/images/amendoim.jpeg"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 9,
    name: "Alergia a proteína do ovo",
    title: "Alergia a proteína do ovo",
    image: require("@/assets/images/intolerancia-a-lactose.jpg"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 10,
    name: "Alergia ao glúten",
    title: "Alergia ao glúten",
    image: require("@/assets/images/gluten.jpg"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 11,
    name: "Alergia a crustáceos",
    title: "Alergia a crustáceos",
    image: require("@/assets/images/crustáceos.jpg"),
    type: "condition",
    description: "TODO",
  },
  {
    id: 12,
    name: "Alergia a oleoginosas",
    title: "Alergia a oleoginosas",
    image: require("@/assets/images/oleaginosas.jpg"),
    type: "condition",
    description: "TODO",
  },
];
