export const productsDb: Array<Product> = [
  {
    id: 1,
    codeType: "GTIN/EAN",
    code: 7896256601824,
    image: require("@/assets/images/7896256601824.png"),
    name: "LEITE UHT SEMIDESNATADO ZERO LACTOSE TIROL CAIXA COM TAMPA 1L",
    category: "Leite longa vida (UHT)",
    brand: "TIROL",
    GPC: "Leite / Substitutos do leite (Não perecível)",
    description:
      "O leite semidesnatado 0% lactose Tirol é feito para pessoas que não possuem a capacidade de processar o açúcar do leite, a chamada intolerância à lactose.",
    ingredients: [
      {
        name: "LEITE PASTEURIZADO SEMIDESNATADO",
        associatedWith: [
          { type: "restriction", id: 1, severity: "red" },
          { type: "pattern", id: 1, severity: "red" },
          { type: "pattern", id: 2, severity: "red" },
        ],
      },
      { name: "TRIPOLIFOSFATO DE SÓDIO INS 451I" },
      { name: "CITRATO DE SÓDIO INS 331III" },
      { name: "FOSFATO MONOSSÓDICO INS 339I" },
      { name: "DIFOSFATO DISSÓDICO INS 450I" },
    ],
    servingSize: { unit: "ml", value: 200 },
    nutritionFacts: [
      {
        type: "Valor energético",
        value: 79,
        unit: "kcal",
        dailyValue: 4,
      },
      {
        type: "Carboidratos",
        value: 9,
        unit: "g",
        dailyValue: 3,
      },
      {
        type: "Açúcares totais",
        value: 9,
        unit: "g",
        dailyValue: null,
      },
      {
        type: "Açúcares adicionados",
        value: 0,
        unit: "g",
        dailyValue: 0,
      },
      {
        type: "Galactose",
        value: 4.6,
        unit: "g",
        dailyValue: null,
      },
      {
        type: "Glicose",
        value: 4.4,
        unit: "g",
        dailyValue: null,
      },
      {
        type: "Lactose",
        value: 0,
        unit: "g",
        dailyValue: "**",
      },
      {
        type: "Proteínas",
        value: 6.2,
        unit: "g",
        dailyValue: 12,
      },
      {
        type: "Gorduras totais",
        value: 2,
        unit: "g",
        dailyValue: 3,
      },
      {
        type: "Gorduras saturadas",
        value: 1.4,
        unit: "g",
        dailyValue: 7,
      },
      {
        type: "Gorduras trans",
        value: 0,
        unit: "g",
        dailyValue: 0,
      },
      {
        type: "Fibras Alimentares",
        value: 0,
        unit: "g",
        dailyValue: 0,
      },
      {
        type: "Sódio",
        value: 136,
        unit: "mg",
        dailyValue: 7,
      },
      {
        type: "Cálcio",
        value: 230,
        unit: "mg",
        dailyValue: 23,
      },
    ],
    allergenInfo:
      "CONTÉM LEITE. NÃO CONTÉM GLÚTEN. DIABÉTICOS: CONTÉM GLICOSE E GALACTOSE. CONSUMIR PREFERENCIALMENTE SOB ORIENTAÇÃO NUTRICIONAL OU MÉDICA.",
  },
  {
    id: 2,
    codeType: "GTIN/EAN",
    code: 7898080640932,
    image: require("@/assets/images/7898080640932.png"),
    name: "LEITE UHT SEMIDESNATADO ZERO LACTOSE 1L ITALAC",
    category: "Leite longa vida (UHT)",
    brand: "ITALAC",
    GPC: "Leite / Substitutos do leite (Não perecível)",
  },
  {
    id: 3,
    codeType: "GTIN/EAN",
    code: 7896256601824,
    image: require("@/assets/images/7896256601824.png"),
    name: "LEITE UHT SEMIDESNATADO ZERO LACTOSE PIRACANJUBA CAIXA COM TAMPA 1L",
    category: "Leite longa vida (UHT)",
    brand: "TIROL",
    GPC: "Leite / Substitutos do leite (Não perecível)",
  },
  {
    id: 4,
    codeType: "GTIN/EAN",
    code: 7891000066560,
    image: require("@/assets/images/7891000066560.png"),
    name: "LEITE UHT INTEGRAL NINHO CAIXA 1L",
    category: "Leite longa vida (UHT)",
    brand: "TIROL",
    GPC: "Leite / Substitutos do leite (Não perecível)",
  },
  {
    id: 5,
    codeType: "GTIN/EAN",
    code: 7898080640017,
    image: require("@/assets/images/7898080640017.png"),
    name: "LEITE UHT INTEGRAL 1L COM TAMPA ITALAC",
    category: "Leite longa vida (UHT)",
    brand: "ITALAC",
    GPC: "Leite / Substitutos do leite (Não perecível)",
  },

  {
    id: 6,
    codeType: "GTIN/EAN",
    code: 7891203010056,
    image: require("@/assets/images/7891203010056.png"),
    name: "PÃO DE FORMA PANCO PREMIUM PACOTE 500G",
    category: "Pães Industrializados",
    brand: "PANCO",
    GPC: "Alimentos / Bebidas / Tabaco",
  },
  {
    id: 7,
    codeType: "GTIN/EAN",
    code: 7896002360326,
    image: require("@/assets/images/7896002360326.png"),
    name: "PÃO DE FORMA TRADICIONAL PULLMAN PACOTE 480G",
    category: "Pães Industrializados",
    brand: "PULLMAN",
    GPC: "Pães (Não Perecíveis)",
  },

  {
    id: 8,
    codeType: "GTIN/EAN",
    code: 7896066301402,
    image: require("@/assets/images/7896066301402.png"),
    name: "PÃO DE FORMA MULTIGRÃOS SEM GLÚTEN ZERO LACTOSE WICKBOLD PACOTE 300G",
    category: "Pães Industrializados",
    brand: "WICKBOLD",
    GPC: "Pães (Não Perecíveis)",
  },
  {
    id: 9,
    codeType: "GTIN/EAN",
    code: 7896066301396,
    image: require("@/assets/images/7896066301396.png"),
    name: "PÃO DE FORMA ORIGINAL SEM GLÚTEN ZERO LACTOSE WICKBOLD PACOTE 300G",
    category: "Pães Industrializados",
    brand: "WICKBOLD",
    GPC: "Pães (Não Perecíveis)",
  },
];
